### ISSUE TITLE
Issues using TCMU

### ISSUE THREAD

**Issue by mscaff0** [dry-75/imx-m4fwloader#3]
While using the program to write code to OCRAM it works fine, but when writing to the TCM I'm restricted to the lower portion of it.
I know that it is better to leave all the code into the lower half and data on the upper one, but thing it shouldn't be enforced. Mostly because code on TCMU still a lot faster than OCRAM and also, the NXP samples generate code where the initialised data is in place and not copied on startup (as it would be in a flash based device), so your code has always more than 32Kb.
Tried to just change the 32Kb limit in the source, but now I get a core dump. I guess that now I should play a little bit with the DTS file and the memory definitions, but I have no clue where to start.

**Comment by dry-75** [comment]
Hi,

> the NXP samples generate code where the initialised data is in place and not copied on startup (as it would be in a flash based device), so your code has always more than 32Kb.

This must be new/updated BSP then. The BSP and samples from 2017/18 release for iMX7D use startup file which definitely does copy data. That's the BSP I used last (or still using), and on startup the code copies data from code/text area to data.  ( It it wasteful but doesn't hurt much and it didn't bother me for my app).

> ..I'm restricted to the lower portion of it.

Actually, I glanced over the code and there isn't much that should prevent you loading 64Kb, besides the printf from main() that only 32Kb supported, and the filesize check used when you don't specify the target load address - give 0.  But if you pass your target load address (TCM) and hopefully your binary is 64Kb or less, then it should work, without changing any code.  (but  I've never used full TCM for code)

> I guess that now I should play a little bit with the DTS file and the memory definitions, but I have no clue where to start.

Disable TCM memory in DTS, that should be all needed.  It's a one line/one word change.

I want to mention you should check the info on my wiki of this tool - you likely better to go with remoteproc in kernel to load the M4 firmware for you.
